import mongoose from 'mongoose';

const interviewSchema = new mongoose.Schema(
   {
      userId: {
         type: mongoose.Schema.Types.ObjectId,
         ref: 'User',
         required: true,
         index: true,
      },
      clerkId: {
         type: String,
         required: true,
         index: true,
      },
      // Interview Configuration
      interviewType: {
         type: String,
         required: true,
         trim: true,
         default: 'General Interview',
      },
      language: {
         type: String,
         required: true,
         default: 'english',
         enum: ['english'], // Can expand later
      },
      region: {
         type: String,
         required: true,
         default: 'india',
         enum: ['india'], // Can expand later
      },
      complexity: {
         type: String,
         required: true,
         enum: ['beginner', 'intermediate', 'pro'],
         default: 'beginner',
      },
      // User Profile Data (snapshot for interview)
      candidateInfo: {
         name: {
            type: String,
            required: true,
         },
         skills: [
            {
               type: String,
            },
         ],
         experience: [
            {
               company: String,
               position: String,
               duration: String,
               responsibilities: [String],
            },
         ],
         summary: {
            type: String,
         },
      },
      // Interview Status
      status: {
         type: String,
         enum: ['initiated', 'in-progress', 'completed', 'cancelled'],
         default: 'initiated',
      },
      // Interview Questions (generated by AI)
      questions: [
         {
            questionNumber: {
               type: Number,
               required: true,
            },
            question: {
               type: String,
               required: true,
            },
            category: {
               type: String,
               enum: ['common', 'technical', 'behavioral', 'experience-based'],
               default: 'technical',
            },
            expectedAnswer: {
               type: String,
            },
            userAnswer: {
               type: String,
            },
            score: {
               type: Number,
               min: 0,
               max: 10,
            },
         },
      ],
      // Interview Results (to be filled after completion)
      score: {
         type: Number,
         min: 0,
         max: 100,
      },
      feedback: {
         type: String,
      },
      duration: {
         type: Number, // in minutes
      },
      completedAt: {
         type: Date,
      },
   },
   {
      timestamps: true,
   }
);

// Indexes for faster queries
interviewSchema.index({ userId: 1, createdAt: -1 });
interviewSchema.index({ clerkId: 1, createdAt: -1 });
interviewSchema.index({ status: 1 });

export const Interview = mongoose.model('Interview', interviewSchema);
